spring.application.name=spring_ai-elasticsearch-vector-search

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# Ollama
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.2:3b
spring.ai.ollama.chat.options.num-ctx=4096
spring.ai.ollama.embedding.model=nomic-embed-text

spring.elasticsearch.uris=http://localhost:9200
spring.elasticsearch.username=elastic
spring.elasticsearch.password=${ELASTICSEARCH_PASSWORD}
spring.ai.vectorstore.elasticsearch.initialize-schema=true
spring.ai.vectorstore.elasticsearch.dimensions=768

management.endpoints.web.exposure.include=*

# Docling microservice
docling.service.url=http://localhost:8001

# Log livello DEBUG per vedere i JSON completi di Docling e UnifiedDocumentJson
logging.level.elastic.rag.docling.DoclingController=DEBUG
logging.file.name=elastic-vector-demo.log
